package threemfparser

import (
	"archive/zip"
	"bytes"
	"testing"
)

func TestParse3MF_BambuStudio(t *testing.T) {
	buf := new(bytes.Buffer)
	zw := zip.NewWriter(buf)

	// Create Metadata/slice_info.config
	sliceConfig := `<?xml version="1.0" encoding="UTF-8"?>
<config>
  <header>
    <plate>
      <index>1</index>
      <prediction>20280</prediction>
      <weight>84.84</weight>
    </plate>
  </header>
  <plate>
    <filament id="1" type="PLA" color="#FFFFFF" used_g="84.84" used_m="28.4" />
  </plate>
</config>`

	f, err := zw.Create("Metadata/slice_info.config")
	if err != nil {
		t.Fatalf("Erro ao criar arquivo no zip: %v", err)
	}
	f.Write([]byte(sliceConfig))

	// Create Metadata/project_settings.config with the 5 core tabs
	projSettings := `{
  "layer_height": "0.16",
  "initial_layer_print_height": "0.20",
  "line_width": "0.42",
  "seam_position": "aligned",
  "wall_loops": "3",
  "top_shell_layers": "4",
  "bottom_shell_layers": "3",
  "sparse_infill_density": "15%",
  "sparse_infill_pattern": "gyroid",
  "outer_wall_speed": "150",
  "inner_wall_speed": "250",
  "sparse_infill_speed": "270",
  "travel_speed": "500",
  "initial_layer_speed": "50",
  "enable_support": "1",
  "support_type": "tree",
  "support_style": "tree_slim",
  "support_threshold_angle": "30",
  "brim_type": "auto_brim",
  "nozzle_temperature": "220",
  "bed_temperature": "60",
  "printer_model": "Bambu Lab P1S"
}`
	fp, err := zw.Create("Metadata/project_settings.config")
	if err != nil {
		t.Fatalf("Erro ao criar project_settings: %v", err)
	}
	fp.Write([]byte(projSettings))

	// Create 3D/3dmodel.model with some vertices
	modelXML := `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <object id="1" type="model">
      <mesh>
        <vertices>
          <vertex x="0.0" y="0.0" z="0.0" />
          <vertex x="120.0" y="85.5" z="140.2" />
        </vertices>
      </mesh>
    </object>
  </resources>
</model>`

	fm, err := zw.Create("3D/3dmodel.model")
	if err != nil {
		t.Fatalf("Erro ao criar 3dmodel.model no zip: %v", err)
	}
	fm.Write([]byte(modelXML))

	zw.Close()

	// Now parse it
	raw := buf.Bytes()
	reader := bytes.NewReader(raw)
	parsed, err := Parse3MF(reader, int64(len(raw)), "pote_trico.3mf")
	if err != nil {
		t.Fatalf("Parse3MF falhou: %v", err)
	}

	if parsed.ProductWeightGrams != 84.84 {
		t.Errorf("Esperado peso 84.84g, obtido %v", parsed.ProductWeightGrams)
	}
	if parsed.PrintMinutes != 338 {
		t.Errorf("Esperado 338 minutos, obtido %v", parsed.PrintMinutes)
	}
	if parsed.Material != "PLA" {
		t.Errorf("Esperado material PLA, obtido %v", parsed.Material)
	}

	// Test settings tabs
	// Quality
	if parsed.Settings.Quality.LayerHeight != "0.16mm" {
		t.Errorf("Qualidade: esperado 0.16mm, obtido %s", parsed.Settings.Quality.LayerHeight)
	}
	// Strength
	if parsed.Settings.Strength.WallLoops != "3" || parsed.Settings.Strength.InfillPattern != "Gyroid" {
		t.Errorf("Força: esperado 3 paredes e Gyroid, obtido %s / %s", parsed.Settings.Strength.WallLoops, parsed.Settings.Strength.InfillPattern)
	}
	// Speed
	if parsed.Settings.Speed.OuterWallSpeed != "150 mm/s" {
		t.Errorf("Velocidade: esperado 150 mm/s, obtido %s", parsed.Settings.Speed.OuterWallSpeed)
	}
	// Support
	if !parsed.Settings.Support.Enabled || parsed.Settings.Support.SupportType != "Tree" {
		t.Errorf("Suporte: esperado ativado e Tree, obtido %v / %s", parsed.Settings.Support.Enabled, parsed.Settings.Support.SupportType)
	}
	// Others
	if parsed.Settings.Others.PrinterModel != "Bambu Lab P1S" || parsed.Settings.Others.NozzleTemperature != "220 °C" {
		t.Errorf("Outros: esperado Bambu Lab P1S e 220 °C, obtido %s / %s", parsed.Settings.Others.PrinterModel, parsed.Settings.Others.NozzleTemperature)
	}
}

func TestParse3MF_PrusaSlicer(t *testing.T) {
	buf := new(bytes.Buffer)
	zw := zip.NewWriter(buf)

	prusaConfig := `; generated by PrusaSlicer
filament_used_g = 49.06
estimated_printing_time_normal = 3h 13m
layer_height = 0.20
filament_type = PETG
perimeters = 3
fill_density = 15%
fill_pattern = gyroid
support_material = 1
support_material_style = snug
perimeter_speed = 60
temperature = 230
bed_temperature = 75
`
	f, err := zw.Create("Metadata/PrusaSlicer.config")
	if err != nil {
		t.Fatalf("Erro ao criar arquivo: %v", err)
	}
	f.Write([]byte(prusaConfig))
	zw.Close()

	raw := buf.Bytes()
	reader := bytes.NewReader(raw)
	parsed, err := Parse3MF(reader, int64(len(raw)), "pote_cha.3mf")
	if err != nil {
		t.Fatalf("Parse3MF falhou: %v", err)
	}

	if parsed.ProductWeightGrams != 49.06 {
		t.Errorf("Esperado 49.06g, obtido %v", parsed.ProductWeightGrams)
	}
	if parsed.PrintMinutes != 193 {
		t.Errorf("Esperado 193 minutos, obtido %v", parsed.PrintMinutes)
	}
	if parsed.Settings.Strength.WallLoops != "3" {
		t.Errorf("Esperado 3 paredes, obtido %s", parsed.Settings.Strength.WallLoops)
	}
	if !parsed.Settings.Support.Enabled {
		t.Errorf("Esperado suporte habilitado")
	}
	if parsed.Settings.Others.NozzleTemperature != "230 °C" {
		t.Errorf("Esperado 230 °C, obtido %s", parsed.Settings.Others.NozzleTemperature)
	}
}

func TestParse3MF_BambuStudio_Orca_NormalPart(t *testing.T) {
	buf := new(bytes.Buffer)
	zw := zip.NewWriter(buf)

	// 1. model_settings.config with object type="normal_part"
	modelSettings := `<?xml version="1.0" encoding="UTF-8"?>
<config>
  <object id="1" name="Gatinho Decorativo" type="normal_part">
    <metadata key="name" value="Gatinho Decorativo Porta Joia" />
  </object>
</config>`
	f1, _ := zw.Create("Metadata/model_settings.config")
	f1.Write([]byte(modelSettings))

	// 2. slice_info.config with metadata tags and true filament
	sliceInfo := `<?xml version="1.0" encoding="UTF-8"?>
<config>
  <plate>
    <metadata key="prediction" value="7200" />
    <metadata key="weight" value="45.50" />
    <filament id="1" type="PLA Silk" color="#C0C0C0" used_g="45.50" />
  </plate>
</config>`
	f2, _ := zw.Create("Metadata/slice_info.config")
	f2.Write([]byte(sliceInfo))

	// 3. 3D geometry in 3D/Objects/object_1.model (Bambu Studio export structure)
	objModel := `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <object id="2" type="model">
      <mesh>
        <vertices>
          <vertex x="10.0" y="20.0" z="5.0" />
          <vertex x="78.5" y="85.0" z="77.2" />
        </vertices>
      </mesh>
    </object>
  </resources>
</model>`
	f3, _ := zw.Create("3D/Objects/object_1.model")
	f3.Write([]byte(objModel))

	zw.Close()

	raw := buf.Bytes()
	parsed, err := Parse3MF(bytes.NewReader(raw), int64(len(raw)), "gatinho.3mf")
	if err != nil {
		t.Fatalf("Parse3MF falhou: %v", err)
	}

	if parsed.Material != "PLA Silk" {
		t.Errorf("Esperado material 'PLA Silk', mas obteve: '%v'", parsed.Material)
	}
	if parsed.PrintMinutes != 120 {
		t.Errorf("Esperado 120 minutos (7200s), obtido: %v", parsed.PrintMinutes)
	}
	if parsed.ProductWeightGrams != 45.5 {
		t.Errorf("Esperado 45.5g, obtido: %v", parsed.ProductWeightGrams)
	}
	if parsed.DimXMm != 68.5 || parsed.DimYMm != 65.0 || parsed.DimZMm != 72.2 {
		t.Errorf("Dimensões incorretas: %.1f x %.1f x %.1f (esperado 68.5 x 65.0 x 72.2)", parsed.DimXMm, parsed.DimYMm, parsed.DimZMm)
	}
}
